# Generated by Django 3.2.7 on 2021-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='TBD', max_length=512),
            preserve_default=False,
        ),
    ]
