# Generated by Django 3.2.7 on 2021-09-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210917_1349_squashed_0007_auto_20210917_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorship',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='catalog.Authorship', to='catalog.Person'),
        ),
    ]
