# Generated by Django 3.2.7 on 2021-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_rename_authors_book_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='credits',
            new_name='persons',
        ),
    ]
