# Generated by Django 3.2.7 on 2021-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_rename_credits_book_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='?', max_length=256),
            preserve_default=False,
        ),
    ]
