# Generated by Django 3.2.7 on 2021-10-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210930_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('mass-market paperback', 'Mass Market'), ('ebook', 'Ebook')], default='?', max_length=32),
            preserve_default=False,
        ),
    ]
