# Generated by Django 3.2.7 on 2023-04-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20230419_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
