# Generated by Django 3.2.7 on 2021-09-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.series')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ManyToManyField(related_name='books', through='catalog.SeriesMembership', to='catalog.Series'),
        ),
    ]
