# Generated by Django 3.2.7 on 2021-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210918_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.AddField(
            model_name='series',
            name='books',
            field=models.ManyToManyField(related_name='series', through='catalog.SeriesMembership', to='catalog.Book'),
        ),
    ]
