# Generated by Django 3.2.7 on 2021-09-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210918_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='TBD', max_length=32),
            preserve_default=False,
        ),
    ]
