# Generated by Django 3.2.7 on 2021-09-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_subtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authorship',
            new_name='Credit',
        ),
    ]
