# Generated by Django 3.2.7 on 2023-04-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_book_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('mass-market paperback', 'Mass Market'), ('ebook', 'Ebook'), ('map', 'Map'), ('chapbook', 'Chapbook')], max_length=32),
        ),
        migrations.AlterField(
            model_name='credit',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('illustrator', 'Illustrator'), ('annotator', 'Annotator')], default='author', max_length=16),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=4096)),
                ('books', models.ManyToManyField(to='catalog.Book')),
            ],
        ),
    ]
